In [6]:
import pandas as pd

In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB

In [8]:
# 1. Load Data (Manual Train/Test Split)

data = pd.read_excel("iris-train.xlsx")
data_test= pd.read_excel("iris-test.xlsx")

In [9]:
data

     sepallength  sepalwidth  petallength  petalwidth            class
0            5.2         4.1          1.5         0.1      Iris-setosa
1            5.8         4.0          1.2         0.2      Iris-setosa
2            5.4         3.9          1.7         0.4      Iris-setosa
3            5.4         3.9          1.3         0.4      Iris-setosa
4            7.9         3.8          6.4         2.0   Iris-virginica
..           ...         ...          ...         ...              ...
113          5.7         2.8          4.1         1.3  Iris-versicolor
114          5.6         2.8          4.9         2.0   Iris-virginica
115          6.4         2.7          5.3         1.9   Iris-virginica
116          6.3         2.7          4.9         1.8   Iris-virginica
117          6.0         2.7          5.1         1.6  Iris-versicolor

[118 rows x 5 columns]

In [10]:
data.head()

   sepallength  sepalwidth  petallength  petalwidth           class
0          5.2         4.1          1.5         0.1     Iris-setosa
1          5.8         4.0          1.2         0.2     Iris-setosa
2          5.4         3.9          1.7         0.4     Iris-setosa
3          5.4         3.9          1.3         0.4     Iris-setosa
4          7.9         3.8          6.4         2.0  Iris-virginica

In [11]:
x_train = data.iloc[:, :-1].values
y_train = data.iloc[:, -1].values

x_test  = data_test.iloc[:, :-1].values
y_test  = data_test.iloc[:, -1].values

In [ ]:
# Training the model

In [13]:
# 2. Define Models
models = {
    "Random Forest"          : RandomForestClassifier(n_estimators=100, random_state=42),
    "Decision Tree"          : DecisionTreeClassifier(random_state=42),
    "K-Nearest Neighbors"    : KNeighborsClassifier(n_neighbors=5),
    "Support Vector Machine" : SVC(kernel='rbf', random_state=42),
    "Logistic Regression"    : LogisticRegression(max_iter=200, random_state=42),
    "Gradient Boosting"      : GradientBoostingClassifier(n_estimators=100, random_state=42),
    "Naive Bayes"            : GaussianNB(),
}

In [14]:
# 3. Manual Accuracy Function
def manual_accuracy(actual, predicted):
    count = 0
    for i in range(len(actual)):
        if actual[i] == predicted[i]:
            count += 1
    return count * 100 / len(actual)

In [21]:
# 4. Train, Predict & Evaluate Each Model

print(f"{'Model':<26} {'Accuracy (%)'}")


results = []

for name, model in models.items():
    model.fit(x_train, y_train)
    prediction = model.predict(x_test)
    acc = manual_accuracy(y_test, prediction)
    results.append((name, acc))
    print(f"{name:<26} {acc}%")

Model                      Accuracy (%)
Random Forest              93.75%
Decision Tree              90.625%
K-Nearest Neighbors        93.75%
Support Vector Machine     93.75%
Logistic Regression        90.625%
Gradient Boosting          90.625%
Naive Bayes                96.875%

In [22]:
best_model, best_accuracy= max(results, key=lambda x: x[1])
print(f"\nBest Model: {best_model} with Accuracy: {best_accuracy}%")

Best Model: Naive Bayes with Accuracy: 96.875%